## java的异常

java内置了异常处理机制，总是用异常来表示错误。

异常是一种**<u>class</u>**，所以本身带有类型信息。

![image-20220225145523519](../../../../A_Lab/Note/MD_Pic/image-20220225145523519.png)

**Throwable**是异常体系的根，分**Error**和**Exception**两个体系。

```
Error: 解决不了，直接寄了。
	-OutOfMemoryError:内存耗尽
	-NoClassDefFoundError:无法加载某个class
	-StackOverflowError:栈溢出
Exception:
	-数值类型的错误
	-未找到文件
	-读取网络失败
	-数组越界，对null对象调用方法或字段

## Exception
	RuntimeException 及子类: 不需要捕获的异常
	非RuntimeException 及子类: 必须捕获的异常 (Checked Exception)
```



## 捕获异常 try catch

```java
try...catch语句 捕获异常
	try{可能发生异常} catch{捕获对应Exception及其子类}
throws Exception --> 声明可能抛出的Exception

printStackTrace() --> 打印异常栈
```

### 多catch语句

```
可以使用多个catch语句，每个catch语句分别捕获对应的Exception及其子类
但是只有一个catch会被执行！！所以要决定catch的顺序。
Exception的子类在前面，保证能有机会捕捉到。
```

### finally语句

```
1.不是必须的，可有可无
2.总是在最后执行
```

### 捕获多种异常

```java
catch(IOException | NumberFormat Exception e){
	这两个异常的处理逻辑一样，就放一起了
}
```



## 抛出异常

### 异常传播

```
一个方法报异常，如果没有捕获，会不停的把异常抛到上层，一直到被捕获。
```

### 抛出异常

```java
步骤：
    1.创建一个Exception实例
    2.用throw语句抛出
层层嵌套的e.g.
	public class Main() {
		public static void main(String[] args) {
			try {
                process1();
            } catch (Exception e) {
                e.printStackTrace();
            }
		}
		
		public void process1() {
			try {
				process2();
			} catch (NullPointerException e) {
                 // 把NullPointerException的异常传给了IllegalArugmentException
				throw new IllegalArgumentException(e);
			}
		}
        
        public void process2() {
            throw new NullPointerException();
        }
	}
// finally 的内容一定会执行的！
```



### 屏蔽异常 Suppressed Exception

```java
// finally 中的语句出现异常，就会把catch的异常给覆盖掉
// 把catch被覆盖的异常输出出来
public class Main {
    public static void main(String[] args) throws Exception {
        // 创建了一个保存异常的变量
        Exception origin = null;
        try {
            System.out.println(Integer.parseInt("abc"));
        } catch (Exception e) {
            origin = e; // 这里异常就可以保存住
            throw e; // 仍然会被覆盖，但是在下面出现时仍可以跟着输出
        } finally {
            Exception e = new IllegalArgumentException();
            if (origin != null) {
                e.addSuppressed(origin);
            }
            throw e;
        }
    }
}
```

## NullPointerException

```
// 空指针异常，NPE。
// 对象为null时，调用其方法/字段，就会产生Exception
```

## 断言 assert

```java
e.g.
    // AssertError 会带上后面的消息
	assert x >= 0 : "x must >= 0"
# JVM默认关闭断言，遇到assert就忽略
```

## JDK Logging

```java
// java标准库内置 java.util.logging
e.g.
    import java.util.logging.Level;
    import java.util.logging.Logger;
    public class Hello {
        public static void main(String[] args) {
            // 日志对象
            Logger logger = Logger.getGlobal();
            logger.info("start process...");
            logger.warning("memory is running out...");
            logger.fine("ignored.");
            logger.severe("process will be terminated...");
        }
    }
    
```

### commons Logging

```java
// 自动搜索使用Log4j
e.g.
    import org.apache.commons.logging.Log;
    import org.apache.commons.logging.LogFactory;
    public class Main {
        public static void main(String[] args) {
            Log log = LogFactory.getLog(Main.class);
            log.info("start...");
            log.warn("end.");
        }
    }
```

### Log4j

架构：

![image-20220225222217178](../../../../A_Lab/Note/MD_Pic/image-20220225222217178.png)

console：屏幕

file：文件

socket：远程计算机

用对应的配置文件就行

### SLF4J 和Logback

类似上面的日志api和底层